### ISSUE TITLE
Make package versions customizable

### ISSUE THREAD

**Issue by monrax** [RobDickinson/supertanker#8]
Instead of hard-coding the package versions, the user should have the option to modify them as variables. There are two ways to achieve this:

- At build time, as docker ARGs
- At runtime, as ENV vars

These two are not mutually exclusive, as the first one could be the default option that can be overridden through the second one.

**Comment by RobDickinson** [comment]
This is interesting because it gets into both technical limitations and the intent of this project.

While it is technically possible for a container to install packages at runtime, this is somewhat frowned upon:
* Apt needs to run as root
* Runtime user should not have root permissions
* Container security tools (like Docker Scout) prefer an immutable bill of materials

The Graylog server version is currently declared as a docker ARG but the MongoDB version is hardcoded -- this may also require changing the mongo repo registered, and potentially other configuration bits as well? (I'm not sure as I've only tried the one version of MongoDB here 😀)

The intent with supertanker imho isn't to be able to customize every aspect -- a lot of things can be customized with environment variables, but in other places supertanker makes more opinionated recommendations (like using the most-recommended version of Mongo rather than allowing the user to pick any MongoDB version). This makes the user experience really really simple but may not make supertanker the right choice for bespoke configurations.

If there are specific customizations that would be useful, I'd love to open issues for those and discuss.
