### ISSUE TITLE
Test migration to Datanode

### ISSUE THREAD

**Issue by monrax** [RobDickinson/supertanker#9]
Test that supertanker can handle migrations from traditional Graylog+OpenSearch deployments

**Comment by RobDickinson** [comment]
For the purposes of testing datanode migrations, I suspect `docker compose` is going to be the better vehicle.

While supertanker does have configurations for Graylog 6.0 + OpenSearch and Graylog 6.1 + datanode, I've never tested upgrading/migrating from one configuration to the other. (I have tested upgrading between 6.0.x builds and between 6.1.x builds, but not an upgrade from 6.0.x to 6.1.x)

I've heard some positive feedback that supertanker makes it easier to try datanode out for the first time, and that seems like a more proper use for supertanker than trying out migrations between major product versions.

ps. Point taken though -- supertanker could better document its intended use-cases, so that we aren't leaving anybody guessing about what's in scope 😀
